[package]
name = "open-bambu-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3.31"
config = { version = "0.15.19", features = ["toml"] }
lazy_static = "1.5.0"
log = "0.4.28"
env_logger = "0.11.8"
paho-mqtt = "0.13.3"
suppaftp = { path = "../vendor/suppaftp", default-features = false, features = ["native-tls", "deprecated"] }
tempfile = "3.23.0"
rustls-native-certs = "0.8.2"
native-tls = "0.2.14"
anyhow = "1.0.100"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_LibraryLoader"] }
